### ISSUE TITLE
Generate significant fake data for the examples using faker

### ISSUE THREAD

**Issue by kabirbaidhya** [laudio/pyodbc#24]
Generate significant volume (~10,000 records) of data using [faker](https://github.com/joke2k/faker) in each of these available examples:

- [x] [Postgres - Simple Example](https://github.com/laudio/pyodbc/tree/master/examples/app-pg) (#27)
- [x] [Postgres - Data Transfer Example](https://github.com/laudio/pyodbc/tree/master/examples/data-transfer-pg) (#29)
- [x] [MSSQL - Simple Example](https://github.com/laudio/pyodbc/tree/master/examples/app-mssql) (#28) 
- [x] [MSSQL - Data Transfer Example](https://github.com/laudio/pyodbc/tree/master/examples/data-transfer-mssql) (https://github.com/laudio/pyodbc/pull/31)

Reference: https://github.com/joke2k/faker.

Contributors can contribute pick any one (or more) of the examples mentioned above.

**Comment by yankeexe** [comment]
I will take this issue.

**Comment by kabirbaidhya** [comment]
Sure @yankeexe. You can do it in individual pull requests for each one of them. You can take it as four different tasks. You can begin with the first one.

**Comment by kabirbaidhya** [comment]
@yankeexe You can take the remaining tasks now - and I guess it shouldn't take much time either :wink:

**Comment by kabirbaidhya** [comment]
And that's a wrap :tada:. Thanks @yankeexe :+1:
